### ISSUE TITLE
当字段为唯一索引及可以为空时候，这个一直不能通过

### ISSUE THREAD

**Issue by XIAOGUIGUI** [thinkkoa/thinkorm#12]
![afc7c43f-e180-4c43-b55f-6ce134514827](https://user-images.githubusercontent.com/8243283/49193439-09484d00-f3ba-11e8-8a91-5a752a0f2e06.png)

**Comment by richenlin** [comment]
您的字段类型为 integer、float，但是字段又允许为空值，这本身就是矛盾的。integer、float类型的字段应该设置默认值0
