### ISSUE TITLE
关于两个相同版本数据库报错

### ISSUE THREAD

**Issue by Melonxx** [thinkkoa/thinkorm#13]
两个相同版本的mysql5.7，一个是阿里云云数据库，还有一个是阿里云ECS自己安装的数据库，自己的数据库插入部分数据报错（add数据的时候）

![image](https://user-images.githubusercontent.com/30221824/49499822-1aa5c380-f8aa-11e8-9151-9fab102be2a9.png)

一定要插入这一条数据对应数据库 完整的字段才能正常插入

**Comment by richenlin** [comment]
新增数据的时候，ORM默认会参考Model类定义的fields进行组装数据入库。如果某个字段新增的时候没有值，那么可以在Model类定义该字段的默认值default属性。

这样处理的原因是：
1、防止数据类型检查抛出异常。例如postgresql会严格检查数据类型
2、防止数据入库时，数据库定义的非空字段插入null值

**Comment by richenlin** [comment]
er_truncated_wrong_value_for_field incorrect integer value

错误已经描述的很清楚了，数据库中该字段类型为integer，但是你模型类中未定义字段类型，并且默认值为空字符串，导致这个错误

修改默认值为0试试
