### ISSUE TITLE
更新以后increment方法报错。

### ISSUE THREAD

**Issue by Melonxx** [thinkkoa/thinkorm#14]
我在使用这句话时 `await infoActivity.where({'id': 367}).increment('areaid')`
出现报错信息 `Cannot set property 'areaid' of null`

翻阅源码 `liteq/index.js` 发现：

![image](https://user-images.githubusercontent.com/30221824/53320893-f63e0e00-3911-11e9-9afd-6bd8a86d9c4b.png)

如图，打出的 `data` 总为 `null` ，最终导致 `increment` 方法报错

很奇怪，为什么这里的 `data` 为什么是 `null` 按道理来说并不应该啊，即使写成 `await infoActivity.where({'id': 367}).increment('areaid', 123, {})` 打印出来的 `data` 仍为 `null`，但是如果在对象里面随便加点东西`await infoActivity.where({'id': 367}).increment('areaid', 123, {a:123})` 方法就能正常使用且无报错，但是此时打印出来的第三个参数 `data` 为 `{}`，也不是我传入的值。

**Comment by richenlin** [comment]
@Melonxx 已经修复，请升级到3.2.3

**Comment by Melonxx** [comment]
我很好奇，这是为啥呢？按逻辑来 打印出来的data不应该是函数参数传进来的值或者是默认值吗？为什么会出现这样子的情况？

**Comment by richenlin** [comment]
问题不在于传入的值。thinkorm具备自动检查验证数据类型的特性，在validation.js文件的第371行：

如果传入的data为空，那么默认返回了null，导致后续set属性出错，修改为返回{}即可
