### ISSUE TITLE
Inserting a record data will carry the default value of primary key field (v3.2.4)

### ISSUE THREAD

**Issue by Chance722** [thinkkoa/thinkorm#17]
When I insert a record to my database, the primary key field (which should be empty) will set the default value and it lead to an error like this:

![image](https://user-images.githubusercontent.com/27771964/54251512-6f7c6880-4582-11e9-9b80-686a71dcb933.png)

**record_id is a primary key field in my table, with auto-increatement.** 

I tryed to solved the problem and found that when I inserting a record the validData function will set a default value of my primary key field, without judge. 

After I add the primary-key juege it seems to be fine. 

![image](https://user-images.githubusercontent.com/27771964/54251772-427c8580-4583-11e9-8d2e-d7d4c47790ae.png)

**Comment by richenlin** [comment]
This is a bug, please send a pull request.

**Comment by richenlin** [comment]
version: 3.2.5
