### ISSUE TITLE
插入数据时非主键字段检查问题(v3.2.4)

### ISSUE THREAD

**Issue by Chance722** [thinkkoa/thinkorm#19]
如题，在插入数据时我有几个关联外表的id字段（int类型）比如app_id, server_id这些可能默认为null不会去赋值，但是validData方法中的checkData会对所有非主键字段进行类型检测，这样就会导致抛出类型错误。

![image](https://user-images.githubusercontent.com/27771964/54335971-9d86a900-4665-11e9-984e-9869440983ad.png)

我觉得一些不传值的字段，即默认为null时不去做这个判断会不会好点？加上一个判断（事实上是存在这种情况的）

![image](https://user-images.githubusercontent.com/27771964/54336121-0ff78900-4666-11e9-9d18-0d6a60fa859d.png)

**Comment by richenlin** [comment]
这种类型字段在新增数据的时候，理论上来说是应该明确赋值的，因为存在关联定义。如果未定义，建议设置这些字段的默认值，orm会自动修正为默认值（可以顺利通过字段类型判断）

**Comment by Chance722** [comment]
> 这种类型字段在新增数据的时候，理论上来说是应该明确赋值的，因为存在关联定义。如果未定义，建议设置这些字段的默认值，orm会自动修正为默认值（可以顺利通过字段类型判断）

我这边的话是这样的 有一张记录表关联着几个信息id 在插入数据的时候可能会关联一到多个信息 也可能存在不关联的信息种类（此时这种信息id为null） 所以如果设置默认值(defaults: 0) 在进行关联查询的时候也会报错...所以存在不赋值默认值虽然校验通过，但是如果这个字段是关联查询的话也会出现报错的情况。。。

**Comment by richenlin** [comment]
根据你描述，这种场景不具备普遍性。我觉得可以考虑增加一个字段属性，isNull，是否允许为Null值，为True的时候，跳过类型检查

**Comment by Chance722** [comment]
大佬几时添加isNull属性？现在这边是通过判断过滤做处理的（没有提交pr）
![image](https://user-images.githubusercontent.com/27771964/54900647-034d1d80-4f0f-11e9-84bb-ce4f66a595e3.png)

**Comment by richenlin** [comment]
comming soon.

**Comment by richenlin** [comment]
new version: 3.2.6
changelog:
1、字段增加isnull属性，值为true时允许字段赋值null
2、增加migrate create table时，字段属性为null的特性。liteq@2.1.1
3、主键字段或isnull=true的字段，不会赋值默认值，也不会做类型检查；但会做自定义规则检查
