### ISSUE TITLE
插入数据时非主键字段检查问题(v3.2.4)引入isnull之后还是存在问题

### ISSUE THREAD

**Issue by XIAOGUIGUI** [thinkkoa/thinkorm#20]
rflag = !fields[f].pk || fields[f].isnull !== true; 这样写的时候，在非主键、唯一值、可为空的情况下，还是会检查类型和赋予默认值，
// 如果可为空值并且值不存在，直接设置为Null
            if (fields[f].isnull === true && lib.isEmpty(data[f])) {
              rdata[f] = null
              continue
            }

**Comment by richenlin** [comment]
@XIAOGUIGUI thinks!

**Comment by richenlin** [comment]
@XIAOGUIGUI thinks!

**Comment by richenlin** [comment]
@ version 3.2.7
