### ISSUE TITLE
自动建表的时候是否可以指定编码

### ISSUE THREAD

**Issue by jackmo2014** [thinkkoa/thinkorm#4]
mysql不能存储中文的问题一直存在
在网上看了，是由于建表的时候表的编码问题
见：
http://blog.csdn.net/At_Once/article/details/47011289
不知道，thinkorm在自动建表的时候指定编码。

**Comment by richenlin** [comment]
thinkorm支持mysql 数据库的sqlbuild依赖于knex.js，knex.js[文档](http://knexjs.org/#Schema-charset)是支持单表设置字符集的。但是目前thinkorm并未支持递此特性。我们在后续的版本中可以考虑支持。当然您也可以直接pull `thinkorm_adapter_mysql` 进行修改，然后给我们发pull request
