### ISSUE TITLE
API 设计疑问

### ISSUE THREAD

**Issue by NathanLi** [thinkkoa/thinkorm#5]
有点奇怪的地方在于，所有的 sql 操作都依赖于 ‘实例’。实例上，这些操作方法的接入方应该是 类 才对吧。把方法放到实例上，初步看上去很方便，但对于实体类的侵入太重，所有的实例都多出了不必要的信息。比如：`modelName` `fields` 等配置完全可以以类方法的形式返回。

**Comment by richenlin** [comment]
感谢建议！其实更多的还是函数式编程的习惯而已：
1、JS的面向原型和其他语言面向对象不太一样，不管是属性还是方法，都只是原型链上属性而已，class仅仅是语法糖
2、对象是内敛的，每个实例都有各自不同的独立特征，以属性和方法来暴露对外通信接口

3、我想还有一个重要的原因是，原有的thinkorm太重，1.0版本包括2.0版本都是如此，从3.0版本开始，我们开始意识到这一点，刻意的做了一些分离，包括SQLbudil的分离，关联模型的分离。但目前仍然不够

最后，有兴趣的话，一起来维护啊。我们缺人😆
