### ISSUE TITLE
关于 filed字段重命名问题

### ISSUE THREAD

**Issue by Melonxx** [thinkkoa/thinkorm#9]
![image](https://user-images.githubusercontent.com/30221824/44839903-7bea4500-ac72-11e8-93d3-37e5ce525b41.png)

连表查询-左连接，遇到两张表的字段相同时，该如何重命名user表的字段`sex`。否则下一张表的字段会覆盖上一张的...

**Comment by richenlin** [comment]
支持字段自定义alias的：
```
//注意field的写法
userModel
.join([{from: 'Demo', alias: 'demo', on: {demoid: 'id'}, field: ['id as demo.id', 'name'], type: 'left'}])
.where({id: 1, 'demo.name': 'test'})
.find()
```

**Comment by Melonzzz** [comment]
万分感谢，希望能完善到文档中，谢谢

**Comment by richenlin** [comment]
好的。我们的文档确实不够完善，我们会尽快改善的
